# Generated by Django 5.0.2 on 2025-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_average_rating_blog_total_ratings_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='audio',
            field=models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV)', null=True, upload_to='blog_audio/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
